#!/usr/bin/env sh

USAGE="MakeMeta, version 0.1
Usage: ${0} -tv [-f control] [-d .deb]

   -d   .deb      Opens editor with template from file.
   -f   control   Use control as file
   -t             Use the default template
   -v             Verbosity

Creates a metapackage from a control-file, a debian-package or
opens an editor with a template control-file.  Default, or when
control is -, read from standard input.  "

TEMPLATE1="Package: 
Version: 0.1
Section: main
Priority: optional
Architecture: all
Depends: "
TEMPLATE2="Maintainer: $USER
Description: 
"

createpackagelist () {
	while read line ; do TEMPSTRING="$TEMPSTRING $line" ; done ; echo "$TEMPSTRING" | sed -e 's:^ *::' -e 's: :, :g' -e 's:,\s*$::'
}

test -f "$1" && {
	FILE="$1"
	FILETYPE=lst
	test "`echo "$FILE" | sed 's:.*\(.\{7\}\)$:\1:'`" = "control" && FILETYPE=ctl
	file "$FILE" | grep "Debian binary package" > /dev/null && FILETYPE=deb
}

TEMPDIR=`mktemp --tmpdir -d makemeta.XXXX`
CONTROL="$TEMPDIR/DEBIAN/control"
mkdir -p "`dirname $CONTROL`"

test "$FILETYPE" = "ctl" && {
	cp "$FILE" "$CONTROL"
}

test "$FILETYPE" = "deb" && {
	dpkg-deb -e "$FILE" "`dirname $CONTROL`"
}

test "$FILETYPE" = "lst" && {
	echo -n "$TEMPLATE1" >  "$CONTROL"
	cat "$FILE" | createpackagelist >> "$CONTROL"
	echo "$TEMPLATE2" >> "$CONTROL"
}

test -z "$FILETYPE" && {
	FILETYPE=ctl
	echo -n "$TEMPLATE1" >  "$CONTROL"
	test -t 0 && echo >> "$CONTROL" || createpackagelist  >> "$CONTROL"
	echo "$TEMPLATE2" >> "$CONTROL"
	test -t 0 || exec </dev/tty
}

${EDITOR:-editor} "$CONTROL"

dpkg --build "$TEMPDIR" "`cat "$CONTROL" | grep "^Package: " | sed 's/^Package: //'`.deb"

rm -rf "$TEMPDIR"
